export enum ERoutes {
  Index = "/",
  About = "/about",
  Login = "/login",
  Logout = "/logout",
  Signup = "/signup",
  Verify = "/verify",
  ChangePassword = "/change-password",
  ResetPassword = "/reset-password",
  Dashboard = "/dashboard",
  Account = "/dashboard/account",
  Transactions = "/dashboard/transactions",
  Deposit = "/dashboard/deposit",
  Stores = "/dashboard/stores",
  StoreDetails = "/dashboard/store",
  Products = "/dashboard/products",
  ProductDetails = "/dashboard/product",
}
