name: Build and Test
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run the Compose
        env:
          JWT_PVT_KEY: ${{ secrets.JWT_PVT_KEY }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          PUBLIC_RECAPTCHA_CLIENT_KEY: ${{ secrets.PUBLIC_RECAPTCHA_CLIENT_KEY }}
        run: docker compose up --build -d

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright
        run: |
          npm install @playwright/test
          npx -y playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
